version: '3.3'
services:
  scimdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'company_directory'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3377:3306'
